ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "discoveredAt";
ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "conflictNote";
ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "sourceFile";
ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "alertsOn";
ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "emoji";
ALTER TABLE "Wallet" DROP COLUMN IF EXISTS "alias";
